### ISSUE TITLE
Fallo en Inicio de Sesión / Registro en el despliegue sobre Azure

### ISSUE THREAD

**Issue by uo289432** [Arquisoft/wiq_es05a#95]
Tras desplegar la release v1.0 sobre la máquina de Azure hemos comprobado que el sistema de autenticación (tanto inicio de sesión como registro) no funciona. Esta misma versión de la aplicación la hemos desplegado en local utilizando Docker Compose y funciona sin problema alguno por lo que intuimos que el fallo pueda encontrarse en el script release.yml en lo que le respecta a los módulos authservice y userservice.

La versión desplegada puede accederse desde la dirección http://51.143.220.118:3000.
El código de esta versión se encuentra en la rama pública [Pablo-Despliegue](https://github.com/Arquisoft/wiq_es05a/tree/Pablo-Despliegue).

**Comment by augustocristian** [comment]
Estais empleando la conectividad externa  y no la red interna de Docker: 
![image](https://github.com/Arquisoft/wiq_es05a/assets/49859508/dcb68a1a-c87f-497f-a85e-9af48f6b3a9a)
Revisad que habeis modificado/cambiado, el ejemplo de base esto funcionaba.
